# Generated by Django 5.1.15 on 2026-07-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_lessonnote_docuseal_completed_at_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noteassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='noteassignment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='notesignature',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='noteassignment',
            unique_together={('organization', 'external_appointment_id', 'template')},
        ),
    ]
