# Generated by Django 5.1.15 on 2026-07-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tpms_admin_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
