# Generated by Django 5.1.15 on 2026-07-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_programdatafield_is_active_programtag_is_active_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='masterytemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='program',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='programdatafield',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='programtag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='promptingtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='target',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='targetstatus',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='targetstatuschange',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='treatmentarea',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
    ]
