# Generated by Django 5.1.15 on 2026-07-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_target_current_prompt_level_index_target_fading_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='mastery_template',
        ),
        migrations.DeleteModel(
            name='MasteryTemplate',
        ),
    ]
