# Generated by Django 5.1.15 on 2026-07-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_organization'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstaffassignment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
    ]
