# Generated by Django 5.1.15 on 2026-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0005_abcevent_organization_appointment_organization_and_more'),
        ('tenants', '0002_organization_tpms_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcevent',
            name='client_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='behaviorevent',
            name='client_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='abcevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('session_run', 'client_event_id'), name='unique_abcevent_session_client_event_id'),
        ),
        migrations.AddConstraint(
            model_name='behaviorevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('session_run', 'client_event_id'), name='unique_behaviorevent_session_client_event_id'),
        ),
    ]
